services:
  main-app:
    container_name: ${COMPOSE_PROJECT_NAME}-main-app
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh /entrypoint.sh"
    env_file:
      - ../.env
    depends_on:
      - postgres
    networks:
      - backend-network
      - metrics-network
    volumes:
      - ..:/app/

networks:
  backend-network:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_backend
  metrics-network:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_metrics