services:
  postgres:
    image: postgres:latest
    container_name: example-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres_data:
    name: "${COMPOSE_PROJECT_NAME}_postgres_data"   # => 
    labels:
      project: "${COMPOSE_PROJECT_NAME}"      # => 
      role: "database"
    driver: local
    